### PR TITLE
fix: request placeholder resend for messages without encryption (CTWAads)

### LINKED ISSUE #1723: Messages from Facebook/Instagram Ads (“Click to WhatsApp”) are not received until manual reply
Hello,

I'm facing an issue where messages sent to my WhatsApp number via Facebook or Instagram ads (using “Click to WhatsApp” campaigns) are not received in my Baileys client unless I first reply to the contact manually using the official WhatsApp app.

Steps to Reproduce:

1. Run a Facebook or Instagram ad that starts a WhatsApp conversation (the user clicks and sends a message directly from the ad).
2. Wait for a lead to send a message through the ad.
3. Observe that the message appears in the official WhatsApp app, but is not delivered to the Baileys client.
4. Only after replying manually to the user in the official WhatsApp app does Baileys start receiving future messages from this contact.

Additional context:

- In the official WhatsApp app, there's a banner:
"This chat was started from a Facebook or Instagram ad..."

- It seems WhatsApp holds these messages in a “pending” state until a reply is sent or the contact is saved.

Questions:

- Is this a technical limitation from WhatsApp itself, or something that could be handled by Baileys?

- Are there any known workarounds or best practices for receiving these messages programmatically?

Thank you for your help!

### PR DESCRIPTION
**Pull request by jlucaso1**
fixes #1723

messages from Facebook/Instagram Click-to-WhatsApp ads arrive at companion devices without an `enc` node — Meta's ads endpoint doesn't encrypt for linked devices. previously Baileys just ACKed and silently dropped these, so `messages.upsert` was never fired.

the phone has the real message. WhatsApp Web and whatsmeow both request a **placeholder resend** via PDO (Peer Data Operation) to get it. Baileys already had the `requestPlaceholderResend` infrastructure but never called it for this case.

### how it works end-to-end (just for reference)

1. ads message arrives without `enc` node → `decryptables === 0` → CIPHERTEXT stub
2. handler ACKs the stanza and upserts the CIPHERTEXT stub as a placeholder (like WA Web's `processPlaceholderMsg`)
3. `requestPlaceholderResend(cleanKey, msgData)` fires in the background, caching the original message metadata (key w/ LID, pushName, etc.)
4. `messages.update` emits with the `requestId` in `stubParameters[1]` so consumers can correlate
5. after 2s dedup window, PDO request is sent to phone
6. phone responds with `PEER_DATA_OPERATION_REQUEST_RESPONSE_MESSAGE`
7. `processMessage` decodes `webMessageInfoBytes`, merges with cached metadata (preserves LID details the phone may omit)
8. `messages.upsert` fires with the real decoded message

also fixes null safety / cache key bugs in the existing PDO response handler and adds WA Web's filters (excludes `bot_unavailable_fanout`, `hosted_unavailable_fanout`, `view_once_unavailable_fanout`, and messages older than 14 days).

### CODE REVIEW

**Comment by purpshell** [comment]
@jlucaso1 This has been there for ages before. It got removed when the messageRetryManager was introduced. Can we instead handle this in there?

**Comment by purpshell** [comment]
Duplicate of #2292

**Comment by jlucaso1** [comment]
@purpshell  the `requestPlaceholderResend` inside `sendRetryRequest` is never reached for these messages, your commit [f46e8b118c](https://github.com/WhiskeySockets/Baileys/commit/f46e8b118c) added `NO_MESSAGE_FOUND_ERROR_TEXT` to the early return so they never fall through to `sendRetryRequest`.

also WA Web handles unavailable messages separately from retry, it just ACKs them and triggers placeholder resend lazily later, no retry receipt is sent:

```js
// WA Web — unavailable message handling
if (T.isUnavailable) {
    yield processPlaceholderMsg({ type: CIPHERTEXT, ... })
    sendReceipt(D, T, { result: E2EProcessResult.BACKFILL })  // just an ACK, not retry
    return null
}
```

i can route through `messageRetryManager.schedulePhoneRequest()` if you want it centralized there, lmk

**Comment by purpshell** [comment]
> @purpshell the `requestPlaceholderResend` inside `sendRetryRequest` is never reached for these messages, your commit [f46e8b118c](https://github.com/WhiskeySockets/Baileys/commit/f46e8b118c) added `NO_MESSAGE_FOUND_ERROR_TEXT` to the early return so they never fall through to `sendRetryRequest`.
> 
> also WA Web handles unavailable messages separately from retry, it just ACKs them and triggers placeholder resend lazily later, no retry receipt is sent:
> 
> ```js
> // WA Web — unavailable message handling
> if (T.isUnavailable) {
>     yield processPlaceholderMsg({ type: CIPHERTEXT, ... })
>     sendReceipt(D, T, { result: E2EProcessResult.BACKFILL })  // just an ACK, not retry
>     return null
> }
> ```
> 
> i can route through `messageRetryManager.schedulePhoneRequest()` if you want it centralized there, lmk

What you mentioned at the end makes sense, let's use the schedule of the retry manager, would love one place to keep track of these things.

File: src/Socket/messages-recv.ts [hunk 1]
```diff
@@ -1227,6 +1227,42 @@ export const makeMessagesRecvSocket = (config: SocketConfig) => {
...
+						const cleanKey: proto.IMessageKey = {
+							remoteJid: msg.key.remoteJid,
+							fromMe: msg.key.fromMe,
+							id: msg.key.id,
+							participant: msg.key.participant
+						}
+						requestPlaceholderResend(cleanKey)
+							.then(requestId => {
+								if (requestId) {
+									logger.debug({ msgId: msg.key.id, requestId }, 'requested placeholder resend for unavailable message')
```
Comment (purpshell) [inline src/Socket/messages-recv.ts:1285]:
```suggestion
									logger.debug({ msgId: msg.key.id, requestId }, 'requested placeholder resend for unavailable message')
									msg.messageStubParameters[1] = requestId
```

Comment (purpshell) [reply src/Socket/messages-recv.ts:1285]: This is behavior I determined before. You can use the requestId in the stubparam to compare it to the requestId in the incoming event

**Comment by purpshell** [comment]
> ACKs the stanza and returns (no CIPHERTEXT stub upserted)

This might cause issues as iirc PDO responses from the phone usually omit things like LID details so on.

We could cache the message key data and everything around the message itself and then apply the WebMessageInfo.message

thoughts?

File: src/Utils/process-message.ts
Comment (purpshell) [inline src/Utils/process-message.ts:1]: Add debug log for "received placeholder resend" with the same msgId and requestId

Comment (jlucaso1) [reply src/Utils/process-message.ts:1]: done

**Comment by jlucaso1** [comment]
> > ACKs the stanza and returns (no CIPHERTEXT stub upserted)
> 
> This might cause issues as iirc PDO responses from the phone usually omit things like LID details so on.
> 
> We could cache the message key data and everything around the message itself and then apply the WebMessageInfo.message
> 
> thoughts?

yeah makes sense, implemented it. We cache the original msg metadata (key w/ LID, pushName, timestamps etc.) and when the PDO response comes back we just apply the .message from the decoded response onto the cached data

**Comment by irastorzatobias** [comment]
was this tested it? i still have chats without ads, i have to answer them through the app to get the contact... 

im currently on this pr..

 "@whiskeysockets/baileys": "github:WhiskeySockets/Baileys#fix-ads-messages",

**Comment by guilhermebkel** [comment]
Same here, i'm currently using this PR and the issue is still happening

**Comment by irastorzatobias** [comment]
I managed to figure out, that the messages are coming with **absent from node**, so im processing those with this:

```
export const isAbsentMessage = (msg: WAMessage): boolean => {
  return ! msg.key.fromMe &&
    msg.messageStubParameters &&
    Array.isArray(msg.messageStubParameters) &&
    msg.messageStubParameters.some(param => param.toLowerCase().includes('absent'));
};
```


And i sent to the user the classic WhatsApp message:

"Message unavailable, check your device for info".

At least the chat it's not being lost.

**Comment by jword** [comment]
{"level":20,"time":"2026-02-28T00:26:40.594Z","pid":804345,"hostname":"whatsapp","msg":"Added message to retry cache: 64197295620342@lid/AC9C02106EAB48F94B75F1712CA5B120"}
{"level":20,"time":"2026-02-28T00:26:40.594Z","pid":804345,"hostname":"whatsapp","jid":"64197295620342@lid","id":"AC9C02106EAB48F94B75F1712CA5B120","msg":"Added message to recent cache for retry receipts"}
{"level":20,"time":"2026-02-28T00:26:40.595Z","pid":804345,"hostname":"whatsapp","recv":{"tag":"message","attrs":{"from":"64197295620342@lid","type":"text","id":"AC9C02106EAB48F94B75F1712CA5B120","notify":"وضاح حسين بوخمي","sender_pn":"","t":"1772238399"}},"sent":{"id":"AC9C02106EAB48F94B75F1712CA5B120","to":"64197295620342@lid","class":"message","type":"text","from":""},"msg":"sent ack"}
{"level":10,"time":"2026-02-28T00:26:40.595Z","pid":804345,"hostname":"whatsapp","xml":"<ack id='AC9C02106EAB48F94B75F1712CA5B120' to='64197295620342@lid' class='message' type='text' from=''/>","msg":"xml send"}    
{"level":20,"time":"2026-02-28T00:26:42.612Z","pid":804345,"hostname":"whatsapp","msgId":"AC9C02106EAB48F94B75F1712CA5B120","requestId":"3EB0BD1553F8CB16D6A3BF","msg":"requested placeholder resend for unavailable message"}   
{"level":20,"time":"2026-02-28T00:26:50.597Z","pid":804345,"hostname":"whatsapp","messageKey":{"remoteJid":"64197295620342@lid","fromMe":false,"id":"AC9C02106EAB48F94B75F1712CA5B120"},"msg":"PDO message without response after 8 seconds. Phone possibly offline"}

i'm currently using this PR , but this often appears nowadays：Phone possibly offline. 
But the mobile phone is always online
@jlucaso1

**Comment by renatoiub** [comment]
It didn't work that way; it returns error 479. I managed to work around the error, but even with the phone online, I don't receive the original message. I get confirmation that the request was received, but the requested message never arrives.

{
  tag: 'message',
  attrs: {
    id: '3EB0496915F179F812D0E6',
    type: 'text',
    category: 'peer',
    push_priority: 'high_force',
    to: 'XXXXXXXXXX@s.whatsapp.net',
    t: '1773122862'
  },
  content: [
    {
      tag: 'enc',
      attrs: { v: '2', type: 'msg' },
      content: Buffer(115) [Uint8Array] [
         51,  10,  33,   5, 152,  83, 219,  21,  44, 206,   1, 181,
         94, 166, 170, 152, 244,  96, 127, 250,  93, 153,  87,  94,
         94, 219, 249, 198, 178, 208, 145, 213, 214,  47,   6,  15,
         16, 254,   6,  24,   4,  34,  64, 249, 206,  35, 248, 200,
        112,   8,  55,   0,  30, 130,  23, 226, 143, 117,  49, 129,
        128,   1,  37, 203, 236,  28,   1,  10, 236, 229, 200,   7,
         65, 111,   0, 173,  71,  24,  32,  24, 235,  97, 220, 131,
         10,   8, 240,  85,   5,  59, 119,   5,  54, 163, 163,  67,
         42,  21, 136, 170,
        ... 15 more items
      ]
    }
  ]
}



This way, it doesn't return error 479, but it also doesn't return the message. I receive confirmation of receipt of the device, but not the message.

**Comment by alejandro-aurora** [comment]
+1
