### PR TITLE
fix: sending SERVER_ACK to messages.update

### LINKED ISSUE #620: [BUG] messages.update dont listen to status 2
**Describe the bug**
On sending messages with baileys, most of the time it jumps directly from status 1 to status 3, without going through 2.
When I send a message on my cell phone, it correctly goes through the status 2 (1,2 and 3).

### PR DESCRIPTION
**Pull request by MateusFrFreitas**
Fixes #620

### CODE REVIEW

File: src/Utils/generics.ts [hunk 1]
```diff
@@ -316,6 +316,7 @@ export const generateMdTagPrefix = () => {
 }
 
 const STATUS_MAP: { [_: string]: proto.WebMessageInfo.Status } = {
+	'sender': proto.WebMessageInfo.Status.SERVER_ACK,
```
Comment (manfe) [inline src/Utils/generics.ts:319]: I think `sent` makes more sense.

```suggestion
	'sent': proto.WebMessageInfo.Status.SERVER_ACK,
```

Comment (manfe) [reply src/Utils/generics.ts:319]: Or: `server-received`

Comment (MateusFrFreitas) [reply src/Utils/generics.ts:319]: I think it doesn't work because it maps the `MessageReceiptType`:

```typescript
export type MessageReceiptType = 'read' | 'read-self' | 'hist_sync' | 'peer_msg' | 'sender' | 'inactive' | 'played' | undefined
``` 

I would have to change some more code...

Comment (MateusFrFreitas) [reply src/Utils/generics.ts:319]: You can find out its value is 'sender' logging on line 628, file `src/Socket/messages-recv.ts`

```typescript
try {
  await Promise.all([
    processingMutex.mutex(
	async() => {
	  logger.debug(attrs.type) // prints 'sender'

	  const status = getStatusFromReceiptType(attrs.type)
	  ...
```

**Review by purpshell — APPROVED** [review]
Is this why messages are "pending" until they're delivered or read?
